# Required to run your project under the correct environment.
language: php

notifications:
  email: false

# Versions of PHP you want your project run with.
php:
  - 7.0
  - 7.1

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install

# Commands you want to run that will verify your build.
script:
    - composer run-script lint
    - composer run-script test
